### ISSUE TITLE
Number episodes in the schedule

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/styles#353] opened 2018-08-28 18:28 UTC
see swcarpentry/r-novice-gapminder#419

**Comment by fmichonneau** [comment] 2018-08-28 18:28
somewhat related to carpentries/lesson-example#220

**Comment by maxim-belkin** [comment] 2018-08-28 18:39
We already have `{{ lesson_number }}.` in `_includes/syllabus.html` (line 47). `r-novice-gapminder` just has to merge `carpentries/styles`

**Comment by maxim-belkin** [comment] 2018-08-28 18:42
Actually, they have it merged. It's something else that prevents these numbers from showing up

**Comment by maxim-belkin** [comment] 2018-08-28 19:04
In a locally rendered version of `r-novice-gapminder` I see the numbers
<img width="974" alt="image" src="https://user-images.githubusercontent.com/13123663/44744512-d65d9700-aaf4-11e8-93af-8dee1fe903d7.png">
However, this is what I had to do to make it work:

1. Add these 3 lines to `bin/knit_lessons.sh`:
```
+    Rscript -e "install.packages('stringr')"
+    Rscript -e "install.packages('checkpoint')"
+    Rscript -e "install.packages('knitr')"
```
2. 
```
echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile
```
I wonder if the problem is caused by the (versions of) packages that github has installed.

**Comment by brownsarahm** [comment] 2018-08-28 20:16
[Other](https://datacarpentry.org/python-ecology-lesson/) [currently](https://datacarpentry.org/python-socialsci/) [rendered](https://datacarpentry.org/r-socialsci/) [lessons](https://swcarpentry.github.io/python-novice-gapminder/) have the numbers, there appears to be something wrong in that lesson repo not styles.

**Closed** 2021-10-06 15:29 UTC
