### ISSUE TITLE
lesson_initialize.py fails to initialize new lessons

### ISSUE THREAD

**Issue by annefou** [carpentries/styles#336] opened 2018-07-21 17:23 UTC
I probably misunderstood something but I tried to follow instructions given at https://carpentries.github.io/lesson-example/setup.html but it failed to initialize the lesson:

```
$ python bin/lesson_initialize.py
Warning: CODE_OF_CONDUCT.md already exists.
**Exiting without creating files.**
```
So I deleted `CODE_OF_CONDUCT.md` and then it worked:

```
$ rm CODE_OF_CONDUCT.md
$ python bin/lesson_initialize.py
```

**Comment by maxim-belkin** [comment] 2018-08-02 21:07
I'll look into this.

**Comment by maxim-belkin** [comment] 2018-08-02 21:17
You're right, Anne. Francois added `CODE_OF_CONDUCT.md` to the root directory in 4755a6d in an attempt to fix carpentries/styles#300. This whole situation is caused by the approach we're currently employing in that lesson use this repository as their base.

Currently, the solution would be to fix the `lesson_initialize.py` script to handle existence of `CODE_OF_CONDUCT.md` file.

**Comment by rgaiacs** [comment] 2018-08-03 07:35
Thanks for the issue. Fixed by https://github.com/carpentries/styles/pull/338.

**Closed by rgaiacs** 2018-08-03 07:35 UTC
Labels: high priority
