### ISSUE TITLE
add incubator as a "Carpentry" option 

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/styles#435] opened 2019-09-24 21:21 UTC
Could the incubator and labs be set up as options for the carpentry option on the config file?

As I wrote this, I realized it would also then make sense to make a page exist at carpentries-incubator.github.io, which could help with findability and exploration of the lessons.  It could be like the DC workshop overview pages. 

If there's support, I'm happy to 1) work on that page and 2) put in a PR for the options.

_i'll be offline for the next several days, so I won't get to this until October_

**Comment by ErinBecker** [comment] 2019-09-25 00:11
Thanks for your thoughts @brownsarahm! @fmichonneau and I have been discussing this in prep for the community discussions on the Incubator this week. He's either just put in a PR or is in the process of doing so to get incubator and lab set up as options in the config (@fmichonneau - could you please link the PR here?). As soon as we have that merged in, we'll be creating a top-level page to show the Incubator lessons, exactly as you suggested. 😄 I'll let you know if we need any help.

**Comment by fmichonneau** [comment] 2019-09-25 04:19
PR adding the "incubator" option is here: https://github.com/carpentries/carpentries-theme/pull/1/files

To make template updates easier, Erin and and I thought it'd be easier to use the remote Jekyll theme. That's why the PR is against that repo instead of `styles`.

**Comment by brownsarahm** [comment] 2019-10-01 17:08
Is the remote theme ready for use?

**Comment by ErinBecker** [comment] 2019-10-11 23:35
@brownsarahm - several DC lessons are already using the remote theme, so I believe it's ready to use.  However, there isn't much (or any?) documentation of how it works. I'm talking with @fmichonneau about documentation next week.

**Comment by fmichonneau** [comment] 2019-12-13 22:21
There are more details to take into account depending on how old the template is in the lesson but the basic steps to enable remote themes are:

1. make sure you have a `Gemfile` at the root of your lesson
1. make sure that the Makefile uses `bundle exec jekyll serve` or use this command to preview your site locally
2. delete `assets`, `_includes` and `_layout` for your repository
3. add `remote_theme: carpentries/carpentries-theme` to the `_config.yml` file in your repo
1. run `bundle exec jekyll serve` to check that you can render your site locally
1. push the changes to GitHub.

**Closed by fmichonneau** 2019-12-13 22:21 UTC

**Comment by Denubis** [comment] 2020-01-22 03:28
@fmichonneau I wasn't able to replicate those steps. https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml doesn't have remote in it. 

Replication steps:

1. Gemfile manually updated to be exactly the one in styles.
2. Copied config from boilerplate, added remote_theme at bottom.
3. Removed assets, _includes, _layout.
4. Using rbenv, installed 2.7.0
```
brian@1602019:~/People/swc/2020-01-27-PreAlpha-Workshop/capstone-novice-spreadsheet-biblio$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
```
5. `$ bundle install`
6. `$ bundle exec jekyll s`

Results in: 
```
/home/brian/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-3.6.2/lib/jekyll/tags/include.rb:118:in `locate_include_file': Could not locate the included file 'links.md' in any of ["/home/brian/People/swc/2020-01-27-PreAlpha-Workshop/capstone-novice-spreadsheet-biblio/_includes", "/home/brian/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-theme-primer-0.5.2/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. (IOError)
```

Following instructions from https://github.com/benbalter/jekyll-remote-theme,

I had to add `gem "jekyll-remote-theme"` to the gemfile and
```
plugins:
  - jekyll-remote-theme
```

Not sure how to turn this into a pull request. Do we change the boilerplate and gemfile in styles?

**Comment by maxim-belkin** [comment] 2020-01-22 15:34
Brian, your error message is caused by the deletion of `_includes` directory because our lessons currently need `_includes/links.md` file.

**Comment by Denubis** [comment] 2020-01-22 21:32
Ah, so @fmichonneau's instructions were not ready for primetime? Fair enough. (The remote theme, after updating gemfile and bundles did work without the include)

**Comment by brownsarahm** [comment] 2020-01-22 22:18
My understanding is that remote theme and styles are not the same thing, there is a separate repo for [remote theme](https://github.com/carpentries/carpentries-theme/pull/1/files). 

When @fmichonneau updated my project in the incubator it did not include `gem "jekyll-remote-theme"`  and it works: https://github.com/carpentries-incubator/python-packaging-publishing/pull/48/files

the remote theme, does not require `_includes/`

**Comment by Denubis** [comment] 2020-01-22 23:22
@brownsarahm did you locally compile? I expect github has that gem by default, but if you did locally compile I'm... going to have to scratch my head some more and ask more questions.

I concur that use of the remote theme, when it works, does not require `_includes/` -- and with appropriate gems (maybe?) it works on github and local compile.

**Comment by brownsarahm** [comment] 2020-01-22 23:47
Yes mine compiles locally, it does have one warning `Invalid theme folder: _sass` but it renders appropriately.

**Comment by Denubis** [comment] 2020-01-23 00:22
Ah hah. I just looked in that pull request. The github pages gem (https://pages.github.com/versions/) has remote-themes as one of its components. Clearly I've done something odd that I had to add it manually. 

Sorry for the trouble.

**Comment by maxim-belkin** [comment] 2020-01-23 03:42
Apologies for going radio silent -- have been having issues with Firefox...

First of all -- my apologies... it looks like my comment confused you. I didn't mean that the remote theme requires the `_includes` directory. Our lessons require `_includes/links.md` file -- every episode is supposed to have `{% include links.md %}` at the very end -- and the error message that you were getting reports that it can not find this file. I didn't try to "debug" further as I don't know your setup and, technically, a lot of things could cause it.

> Clearly I've done something odd that I had to add it manually. 

Your error message can be replicated by not adding `remote_theme` line to the `_config.yml` file:

> Liquid Exception: Could not locate the included file 'links.md' in any of ["/Users/mbelkin/git/carpentries/swc/python-novice-inflammation/_includes", "/Users/mbelkin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jekyll-theme-primer-0.5.4/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /Users/mbelkin/git/carpentries/swc/python-novice-inflammation/_episodes/01-intro.md

So, perhaps you didn't hit "Save" / `:wq` / `:x` / <kbd>Ctrl</kbd>+<kbd>S</kbd>.

Again, my apologies for the confusion.
