### ISSUE TITLE
About page need to mention The Carpentries

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/styles#311] opened 2018-06-22 21:06 UTC
https://github.com/carpentries/styles/blob/gh-pages/_includes/carpentries.html should mention The Carpentries now that Software Carpentry and Data Carpentry merged.

@fmichonneau I'm assigning this to you but you can reassign it to another staff.

**Comment by fmichonneau** [comment] 2018-06-22 21:24
@weaverbel could you please provide me with some text to describe "The Carpentries" to go on the "About" page that comes with each lesson? For instance: http://www.datacarpentry.org/r-raster-vector-geospatial/about/index.html

(if you think some edits are needed to the other carpentries listed, please let me know as well).

**Comment by weaverbel** [comment] 2018-06-25 00:15
Sure. How is this?

The Carpentries comprises Software Carpentry and Data Carpentry, communities of Instructors, Trainers, Maintainers, helpers, and supporters who share a mission to teach foundational coding and data science skills to researchers. In January, 2018,  The Carpentries was formed by the merger of Software Carpentry and Data Carpentry.

While individual lessons and workshops continue to be run under each lesson project, The Carpentries provide overall governance, as well as support for instructor training and mentoring. Memberships are joint, and the Carpentries project maintains a shared Code of Conduct. The Carpentries is a fiscally sponsored project of Community Initiatives, a registered 501(c)3 non-profit based in California, USA.

**Comment by weaverbel** [comment] 2018-06-25 00:16
I will also suggest some edits to the others.

**Comment by weaverbel** [comment] 2018-06-25 01:28
OK, I have rewritten all three: please note change of URL for LC @fmic_

Since 1998, Software Carpentry has been teaching researchers across all disciplines the foundational coding skills they need to get more done in less time and with less pain. Its volunteer instructors have run hundreds of events for thousands of learners around the world. Now that all research involves some degree of computational work, whether with big data, cloud computing, or simple task automation, these skills are needed more than ever.

Data Carpentry develops and teaches workshops on the fundamental data skills needed to conduct research. Its target audience is researchers who have little to no prior computational experience, and its lessons are domain specific, building on learners' existing knowledge to enable them to quickly apply skills learned to their own research. Data Carpentry workshops take researchers through the entire data life cycle.

Library Carpentry (https://librarycarpentry.org/) comprises a group of librarians, repository managers, metadata librarians, research data managers, and other information workers who are committed to teaching and developing a range of lessons designed to help librarians develop skills around coding, task automation, and data analysis, and help them work more effectively with IT and systems colleagues. The training has two aims: to improve efficiency and to help librarians to teach others these foundational skills. Increasingly the information researchers want is in data they already have, can get (from instruments and sensors), or can generate. Data-savvy librarians can assist with that work.

**Comment by weaverbel** [comment] 2018-06-25 23:59
After a meeting today, there is now this wording @fmichonneau . So let's go with this wording.

Library Carpentry (https://librarycarpentry.org/) develops lessons and teaches workshops for and with people working in library- and information-related roles. Our goal is to create an on-ramp to empower this community to use software and data in their own work as well as be advocates for and train others in efficient, effective and reproducible data and software practices.

**Comment by maxim-belkin** [comment] 2018-06-26 13:27
LC description is the only one that uses "Our" and has a link in its description. I think it'll read better if all three descriptions are a tad more similar.

**Comment by fmichonneau** [comment] 2018-06-27 19:45
Thanks, @weaverbel. I replaced the "Our" with "Its" following @maxim-belkin's suggestion.

**Closed** 2018-06-28 01:04 UTC
Labels: type:bug
